# Load single spectra

To see the emission after scanning (for a Map, for Streak camera acquisiton).
To see the emission damage after exposure.

Import packages:

In [29]:
%matplotlib qt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os, glob
sns.set(style='whitegrid', context='paper')
import addcopyfighandler

## Loading HYPCard files

In [3]:
# PARAMS
root = os.path.abspath('G:\My Drive\PhD')
session = r'projects\external_measurements\20211118_CL_Mn_doped_NCs_Sascha'
stacks_folder = 'STREAK/spectra_after_scan'
file_end = '*-V.txt'

files = glob.glob(os.path.join(root, session, stacks_folder, file_end))
files

['G:\\My Drive\\PhD\\projects\\external_measurements\\20211118_CL_Mn_doped_NCs_Sascha\\STREAK/spectra_after_scan\\streak2-after-500ms-2021-11-18-17h04m19s-V.txt',
 'G:\\My Drive\\PhD\\projects\\external_measurements\\20211118_CL_Mn_doped_NCs_Sascha\\STREAK/spectra_after_scan\\streak1-after-500ms-2021-11-18-17h07m17s-V.txt',
 'G:\\My Drive\\PhD\\projects\\external_measurements\\20211118_CL_Mn_doped_NCs_Sascha\\STREAK/spectra_after_scan\\streak3-after-500ms-2021-11-18-17h55m10s-V.txt',
 'G:\\My Drive\\PhD\\projects\\external_measurements\\20211118_CL_Mn_doped_NCs_Sascha\\STREAK/spectra_after_scan\\streak101-after-500ms-2021-11-22-16h32m10s-V.txt',
 'G:\\My Drive\\PhD\\projects\\external_measurements\\20211118_CL_Mn_doped_NCs_Sascha\\STREAK/spectra_after_scan\\streak102-after-500ms-2021-11-22-17h02m31s-V.txt',
 'G:\\My Drive\\PhD\\projects\\external_measurements\\20211118_CL_Mn_doped_NCs_Sascha\\STREAK/spectra_after_scan\\streak104-after-500ms-2021-11-22-17h54m06s-V.txt',
 'G:\\My Drive\\

In [25]:
spectra = {}
for f in files:
    s = np.loadtxt(f)
    x = s[:,:1].flatten()
    y = s[:,1:].flatten()
    key = os.path.basename(f).split('.')[0]
    spectra[key] = [x,y]

spectra

{'streak2-after-500ms-2021-11-18-17h04m19s-V': [array([201.942, 202.472, 203.002, ..., 749.205, 749.746, 750.286]),
  array([310., 309., 310., ..., 310., 311., 311.])],
 'streak1-after-500ms-2021-11-18-17h07m17s-V': [array([201.942, 202.472, 203.002, ..., 749.205, 749.746, 750.286]),
  array([309., 309., 309., ..., 309., 310., 309.])],
 'streak3-after-500ms-2021-11-18-17h55m10s-V': [array([202.441, 202.97 , 203.5  , ..., 749.706, 750.247, 750.787]),
  array([309., 308., 308., ..., 309., 309., 309.])],
 'streak101-after-500ms-2021-11-22-16h32m10s-V': [array([205.431, 205.961, 206.491, ..., 752.714, 753.254, 753.794]),
  array([574., 574., 574., ..., 574., 575., 575.])],
 'streak102-after-500ms-2021-11-22-17h02m31s-V': [array([205.431, 205.961, 206.491, ..., 752.714, 753.254, 753.794]),
  array([573., 573., 573., ..., 574., 574., 574.])],
 'streak104-after-500ms-2021-11-22-17h54m06s-V': [array([205.431, 205.961, 206.491, ..., 752.714, 753.254, 753.794]),
  array([574., 574., 574., ..., 5

# Plot spectra after scan

Plot each map:

In [33]:
for name, s in spectra.items():
    f, axs = plt.subplots(figsize=(4,3))
    axs.plot(s[0], s[1])
    axs.set_title(name)
    axs.set_xlabel('Wavelength (nm)')
    plt.tight_layout()